// AUTO-GENERATED by scripts/gen-handlers-registry.js
// Static imports of every handler file. This forces the Vercel
// bundler to include them all in the function bundle.

import h_0__lib_auth from './_lib/auth.js';
import h_1__lib_bdLocations from './_lib/bdLocations.js';
import h_2__lib_imgbb from './_lib/imgbb.js';
import h_3__lib_middleware from './_lib/middleware.js';
import h_4__lib_payment_helpers from './_lib/payment-helpers.js';
import h_5__lib_prisma from './_lib/prisma.js';
import h_6_admin_settings_edit_mode from './admin/settings/edit-mode.js';
import h_7_auctions__id__bids from './auctions/[id]/bids.js';
import h_8_auctions__id__confirm from './auctions/[id]/confirm.js';
import h_9_auctions__id__index from './auctions/[id]/index.js';
import h_10_auctions__id__place_bid from './auctions/[id]/place-bid.js';
import h_11_auctions__id__reject from './auctions/[id]/reject.js';
import h_12_auctions__id__similar from './auctions/[id]/similar.js';
import h_13_auctions__id__view from './auctions/[id]/view.js';
import h_14_auctions_index from './auctions/index.js';
import h_15_auctions_meta_bd_locations from './auctions/meta/bd-locations.js';
import h_16_auctions_meta_categories from './auctions/meta/categories.js';
import h_17_auctions_meta_locations from './auctions/meta/locations.js';
import h_18_auctions_seller_dashboard from './auctions/seller/dashboard.js';
import h_19_auth_login from './auth/login.js';
import h_20_auth_me from './auth/me.js';
import h_21_auth_register from './auth/register.js';
import h_22_auth_users__id__role from './auth/users/[id]/role.js';
import h_23_auth_users_index from './auth/users/index.js';
import h_24_chats__id__messages from './chats/[id]/messages.js';
import h_25_chats_index from './chats/index.js';
import h_26_cron_expire from './cron/expire.js';
import h_27_health from './health.js';
import h_28_notifications_index from './notifications/index.js';
import h_29_notifications_read_all from './notifications/read-all.js';
import h_30_payments__auctionId__buyer_pay from './payments/[auctionId]/buyer-pay.js';
import h_31_payments__auctionId__contact from './payments/[auctionId]/contact.js';
import h_32_payments__auctionId__seller_pay from './payments/[auctionId]/seller-pay.js';
import h_33_payments__auctionId__status from './payments/[auctionId]/status.js';
import h_34_settings_edit_mode from './settings/edit-mode.js';
import h_35_setup_import_dump from './setup/import-dump.js';
import h_36_setup_migrate from './setup/migrate.js';
import h_37_upload_auction from './upload/auction.js';
import h_38_upload_image from './upload/image.js';
import h_39_watchlist__auctionId_ from './watchlist/[auctionId].js';
import h_40_watchlist_ids from './watchlist/ids.js';
import h_41_watchlist_index from './watchlist/index.js';

const HANDLERS = {
  '_lib/auth': h_0__lib_auth,
  '_lib/bdLocations': h_1__lib_bdLocations,
  '_lib/imgbb': h_2__lib_imgbb,
  '_lib/middleware': h_3__lib_middleware,
  '_lib/payment-helpers': h_4__lib_payment_helpers,
  '_lib/prisma': h_5__lib_prisma,
  'admin/settings/edit-mode': h_6_admin_settings_edit_mode,
  'auctions/[id]/bids': h_7_auctions__id__bids,
  'auctions/[id]/confirm': h_8_auctions__id__confirm,
  'auctions/[id]/index': h_9_auctions__id__index,
  'auctions/[id]/place-bid': h_10_auctions__id__place_bid,
  'auctions/[id]/reject': h_11_auctions__id__reject,
  'auctions/[id]/similar': h_12_auctions__id__similar,
  'auctions/[id]/view': h_13_auctions__id__view,
  'auctions/index': h_14_auctions_index,
  'auctions/meta/bd-locations': h_15_auctions_meta_bd_locations,
  'auctions/meta/categories': h_16_auctions_meta_categories,
  'auctions/meta/locations': h_17_auctions_meta_locations,
  'auctions/seller/dashboard': h_18_auctions_seller_dashboard,
  'auth/login': h_19_auth_login,
  'auth/me': h_20_auth_me,
  'auth/register': h_21_auth_register,
  'auth/users/[id]/role': h_22_auth_users__id__role,
  'auth/users/index': h_23_auth_users_index,
  'chats/[id]/messages': h_24_chats__id__messages,
  'chats/index': h_25_chats_index,
  'cron/expire': h_26_cron_expire,
  'health': h_27_health,
  'notifications/index': h_28_notifications_index,
  'notifications/read-all': h_29_notifications_read_all,
  'payments/[auctionId]/buyer-pay': h_30_payments__auctionId__buyer_pay,
  'payments/[auctionId]/contact': h_31_payments__auctionId__contact,
  'payments/[auctionId]/seller-pay': h_32_payments__auctionId__seller_pay,
  'payments/[auctionId]/status': h_33_payments__auctionId__status,
  'settings/edit-mode': h_34_settings_edit_mode,
  'setup/import-dump': h_35_setup_import_dump,
  'setup/migrate': h_36_setup_migrate,
  'upload/auction': h_37_upload_auction,
  'upload/image': h_38_upload_image,
  'watchlist/[auctionId]': h_39_watchlist__auctionId_,
  'watchlist/ids': h_40_watchlist_ids,
  'watchlist/index': h_41_watchlist_index,
};

export default HANDLERS;
